"""add tax rate and treasury to countries

Revision ID: 2698e41c4930
Revises: 73acd6033868
Create Date: 2026-01-02 13:11:39.424201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2698e41c4930'
down_revision: Union[str, None] = '73acd6033868'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Добавляем колонки с серверным значением по умолчанию, чтобы избежать ошибки NotNullViolation
    op.add_column('meme_countries', sa.Column('tax_rate', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('meme_countries', sa.Column('treasury', sa.BigInteger(), nullable=False, server_default='0'))

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meme_countries', 'treasury')
    op.drop_column('meme_countries', 'tax_rate')
    # ### end Alembic commands ###
