"""Add country model, reviews and rating

Revision ID: 45c5c259048b
Revises: 5c3a7b12dee9
Create Date: 2025-12-05 00:52:19.180036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45c5c259048b'
down_revision: Union[str, None] = '5c3a7b12dee9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # --- 1. СОЗДАНИЕ НОВЫХ ТАБЛИЦ (ЗАКОММЕНТИРОВАНО - ТАБЛИЦЫ УЖЕ СУЩЕСТВУЮТ) ---
    
    # op.create_table('memecountries',
    # sa.Column('country_id', sa.Integer(), nullable=False),
    # sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    # sa.Column('chat_id', sa.BigInteger(), nullable=False),
    # sa.Column('name', sa.String(length=100), nullable=False),
    # sa.Column('description', sa.String(length=1000), nullable=True),
    # sa.Column('ideology', sa.String(length=100), nullable=True),
    # sa.Column('influence_points', sa.Integer(), nullable=True),
    # sa.Column('avg_rating', sa.Float(), nullable=True),
    # sa.Column('total_reviews', sa.Integer(), nullable=True),
    # sa.Column('avatar_url', sa.String(length=255), nullable=True),
    # sa.Column('map_url', sa.String(length=255), nullable=True),
    # sa.Column('ruler_id', sa.Integer(), nullable=True),
    # sa.ForeignKeyConstraint(['ruler_id'], ['users.user_id'], ),
    # sa.PrimaryKeyConstraint('country_id'),
    # sa.UniqueConstraint('chat_id'),
    # sa.UniqueConstraint('name')
    # )
    
    # op.create_table('country_reviews',
    # sa.Column('review_id', sa.Integer(), nullable=False),
    # sa.Column('user_id', sa.Integer(), nullable=False),
    # sa.Column('country_id', sa.Integer(), nullable=False),
    # sa.Column('rating', sa.Integer(), nullable=False),
    # sa.Column('created_at', sa.DateTime(), nullable=True),
    # sa.ForeignKeyConstraint(['country_id'], ['memecountries.country_id'], ),
    # sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    # sa.PrimaryKeyConstraint('review_id'),
    # sa.UniqueConstraint('user_id', 'country_id', name='_user_country_uc')
    # )
    
    # --- 2. ИЗМЕНЕНИЕ СУЩЕСТВУЮЩИХ ТАБЛИЦ (Требует batch mode) ---
    
    # Изменение таблицы 'users'
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_country_creation', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('country_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('position', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('is_ruler', sa.Boolean(), nullable=True))
        
        # Индексы и FK
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=False)
        
        # !! ИСПРАВЛЕНО: Добавлено явное имя для внешнего ключа в Batch Mode !!
        batch_op.create_foreign_key('fk_users_country_id', 'memecountries', ['country_id'], ['country_id'])
        
        # Удаление старой колонки (adminlevel)
        batch_op.drop_column('adminlevel')

    # Изменение таблицы 'history'
    with op.batch_alter_table('history', schema=None) as batch_op:
        # op.create_foreign_key(None, 'history', 'users', ['admin_id'], ['user_id']) 
        # Если здесь были другие ALTER-операции, они должны быть тут. 
        # Если нет, блок может быть пустым.
        pass

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Отмена изменений в history
    with op.batch_alter_table('history', schema=None) as batch_op:
        # Здесь должна быть логика отмены FK
        pass
    
    # Отмена изменений в users
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adminlevel', sa.INTEGER(), nullable=True))
        # !! ИСПРАВЛЕНО: Удаление FK по имени !!
        batch_op.drop_constraint('fk_users_country_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_column('is_ruler')
        batch_op.drop_column('position')
        batch_op.drop_column('country_id')
        batch_op.drop_column('last_country_creation')
    
    # Удаление новых таблиц (Теперь это можно оставить, т.к. Alembic знает, что их нужно удалить)
    op.drop_table('country_reviews')
    op.drop_table('memecountries')
    
    # ### end Alembic commands ###