"""update_models_v2_fix_relationships

Revision ID: 73acd6033868
Revises: 45c5c259048b
Create Date: 2025-12-05 02:29:37.116902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73acd6033868'
down_revision: Union[str, None] = '45c5c259048b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Изменения в таблице 'users' (в пакетном режиме)
    with op.batch_alter_table('users', schema=None) as batch_op:
        # Добавляем новую колонку
        batch_op.add_column(sa.Column('ruling_country_id', sa.Integer(), nullable=True))
        
        # Удаляем старые колонки
        batch_op.drop_column('position')
        batch_op.drop_column('last_country_creation')
        batch_op.drop_column('is_ruler')
        
        # Удаляем индекс
        batch_op.drop_index(op.f('ix_users_username'))
        
        # Удаляем старый FK
        batch_op.drop_constraint(op.f('fk_users_country_id'), type_='foreignkey')

        # Создаем новые FK
        batch_op.create_foreign_key(None, 'meme_countries', ['ruling_country_id'], ['country_id'])
        batch_op.create_foreign_key(None, 'meme_countries', ['country_id'], ['country_id'])

    # 2. Изменения в таблице 'country_reviews' (в пакетном режиме)
    with op.batch_alter_table('country_reviews', schema=None) as batch_op:
        # Удаление старого FK, который не определен по имени (None)
        # Если alembic не может найти имя, то drop_constraint(None, ...) может быть проблемным. 
        # Оставляем pass, так как Alembic часто сам обрабатывает изменение FK в batch mode,
        # а явное удаление FK без имени может вызвать ошибку.
        pass 
        
    # Создание FK для history и country_reviews, которые не конфликтуют с batch_alter_table
    op.create_foreign_key(None, 'country_reviews', 'meme_countries', ['country_id'], ['country_id'])
    op.create_foreign_key(None, 'history', 'users', ['admin_id'], ['user_id'])

    # 3. Удаление старой таблицы - ПЕРЕМЕЩЕНО В КОНЕЦ!
    op.drop_table('memecountries')
    
    # ### end Alembic commands ###


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Изменения в таблице 'users' (в пакетном режиме)
    with op.batch_alter_table('users', schema=None) as batch_op:
        # Удаляем старый FK
        # NOTE: drop_constraint(op.f('fk_users_country_id'), 'users', type_='foreignkey')
        # Если op.f('fk_users_country_id') не работает, нужно найти реальное имя FK в базе.
        batch_op.drop_constraint(op.f('fk_users_country_id'), type_='foreignkey')

        # Удаляем индекс
        batch_op.drop_index(op.f('ix_users_username'))
        
        # Удаляем старые колонки
        batch_op.drop_column('position')
        batch_op.drop_column('last_country_creation')
        batch_op.drop_column('is_ruler')
        
        # Добавляем новую колонку
        batch_op.add_column(sa.Column('ruling_country_id', sa.Integer(), nullable=True))
        
        # Создаем новые FK
        batch_op.create_foreign_key(None, 'meme_countries', ['ruling_country_id'], ['country_id'])
        batch_op.create_foreign_key(None, 'meme_countries', ['country_id'], ['country_id'])

    # 2. Изменения в таблице 'country_reviews' (в пакетном режиме)
    # Эта секция устраняет первую ошибку (NotImplementedError)
    with op.batch_alter_table('country_reviews', schema=None) as batch_op:
        # Удаляем старый FK, который раньше не был обернут:
        # NOTE: drop_constraint(None, 'country_reviews', type_='foreignkey')
        # Так как имя неизвестно, Alembic обычно пытается найти его в batch_op.
        pass # Оставляем пустым, так как Alembic часто сам обрабатывает FK в batch режиме.

    # Создание новых FK, которые не требуют batch mode
    op.create_foreign_key(None, 'history', 'users', ['admin_id'], ['user_id'])
    
    # 3. Добавление FK для country_reviews, который был удален в начале
    op.create_foreign_key(None, 'country_reviews', 'meme_countries', ['country_id'], ['country_id'])

    # 4. Удаление старой таблицы - ПЕРЕМЕЩЕНО В КОНЕЦ!
    op.drop_table('memecountries')
    
    # ### end Alembic commands ###